#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry="0"

while [[ $# > 0 ]]; do
	if [[ $1 == "--dry" ]]; then
		dry="1"
	else
		filter="$1"
	fi
	shift
done

log() {
	if [[ $dry == "1" ]]; then
		echo -e "[DRY RUN]: $@"
	else
		echo -e "$@"
	fi
}

execute() {
	log "\x1b[1;43;34mexecute $@\x1b[0m"
	if [[ $dry == "1" ]]; then
		return
	fi
	"$@"
}

log "$script_dir -- $filter"

cd $script_dir
scripts=$(find ./runs -maxdepth 1 -mindepth 1 -executable -type f)

sudo -v
for script in $scripts; do
	if echo "$script" | grep -qv "$filter"; then
		log "filtering $script"
		continue;
	fi

	execute $script
done
