#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
$script_dir/git

config_dir=$HOME/.config
mkdir $config_dir
rm -rf $config_dir/nvim
mkdir $config_dir/nvim
mkdir $config_dir/wezterm
mkdir $config_dir/i3

temp=$HOME/temp_dotfiles_install_dir
mkdir $temp
cd $temp

git clone https://github.com/jschrtke/dotfiles.git --recurse-submodules
cd ./dotfiles
cp -r ./wezterm $config_dir
cp -r ./nvim $config_dir
cp -r ./i3 $config_dir

cd $HOME
rm -rf $temp
