#!/usr/bin/env bash

config_dir=$HOME/.config
mkdir $config_dir
rm -rf $config_dir/nvim
mkdir $config_dir/nvim
mkdir $config_dir/wezterm

temp=$HOME/temp_dotfiles_install_dir
mkdir $temp
cd $temp

git clone https://github.com/jschrtke/dotfiles.git
cd ./dotfiles
cp -r ./wezterm $config_dir
cp -r ./nvim $config_dir

cd $HOME
rm -rf $temp
