#!/usr/bin/env bash

if [ -z "$(which fzf)" ]; then
    script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
    $script_dir/golang
    mkdir -p ~/thirdparty/
    cd ~/thirdparty/
    git clone https://github.com/junegunn/fzf.git
    cd fzf
    make install
    cp ./bin/fzf ~/.local/bin
    if [ -z "$(grep 'eval "$(fzf --bash)"' ~/.bashrc)" ]; then
        echo 'eval "$(fzf --bash)"' >> ~/.bashrc
    fi
else
    echo "fzf is already installed. Skipping..."
fi
