#!/usr/bin/env bash

if [ -z "$(which git)" ]; then
    sudo apt install -y git
    git config --global init.defaultBranchName main

    if [ -z "$(which nvim)" ]; then
        git config --global core.editor "nvim -u NORC"
    fi
else
    echo "git is already installed. Skipping..."
fi
