#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

sudo apt install -y clang cmake ninja-build gettext curl build-essential git

mkdir $HOME/develop/neovim
cd $HOME/develop/neovim
git clone https://github.com/neovim/neovim.git
cd neovim

git checkout stable
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

