#!/usr/bin/env bash

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

sudo apt upgrade
sudo apt update -y
sudo apt install -y clang cmake ninja-build gettext curl build-essential git

mkdir $HOME/develop/neovim
cd $HOME/develop/neovim
git clone https://github.com/neovim/neovim.git
cd neovim
git checkout v0.11.0

git checkout stable
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install

dev_dir=$HOME/develop/js
mkdir $dev_dir
cd $dev_dir
git clone https://github.com/jschrtke/dotfiles.git
cd ./dotfiles
mkdir $HOME/.config
mkdir $HOME/.config/nvim
cp -r ./nvim $HOME/.config/
